[package]
name = "cycle-tracking-host"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
zkm2-sdk = { workspace = true }

[build-dependencies]
zkm2-build = { workspace = true }
