[package]
name = "uint256-arith-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
zkm2-zkvm = { path = "../../../../crates/zkvm/entrypoint" }
zkm2-derive = { path = "../../../../crates/derive" }
crypto-bigint = "0.6.0-pre.12"
