[package]
name = "groth16-verifier"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
zkm2-zkvm = { path = "../../../crates/zkvm/entrypoint" }
zkm2-verifier =  { path = "../../../crates/verifier" }
