[package]
name = "bn254-mul-test"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
zkm-zkvm = { path = "../../../../crates/zkvm/entrypoint" }
zkm-lib = { path = "../../../../crates/zkvm/lib" }
zkm-derive = { path = "../../../../crates/derive" }
