[workspace]
members = [
  "revme",
  "sha2-rust",
  "sha2",
  "sha-extend",
  "keccak-permute",
  "keccak256",
  "panic",
  "sha-compress",
  "sha2-precompile",
  "fibonacci",
]
resolver = "2"

[workspace.package]
version = "1.1.0"
edition = "2021"
