[package]
name = "json-host"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
serde_json = { workspace = true }
zkm-sdk = { workspace = true }
lib = { path = "../lib", package = "json-lib" }

[build-dependencies]
zkm-build = { workspace = true }
