[package]
name = "sha2-test"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
zkm2-zkvm = { path = "../../../../crates/zkvm/entrypoint" }
hex-literal = "0.4.1"
sha2 = { git = "https://github.com/succinctbot/RustCrypto-hashes.git" }
hex = "0.4.3"
