use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ProofBn254 {
    Plonk(PlonkBn254Proof),
    Groth16(Groth16Bn254Proof),
    DvSnark(DvSnarkBn254Proof),
}

/// A zero-knowledge proof generated by the PLONK protocol with a Base64 encoded gnark PLONK proof.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PlonkBn254Proof {
    /// `[vkey_hash, committed_values_digest, vk_root]`.
    ///
    /// The third is the recursion verifying-key-allowlist root: inside the
    /// tree it is a prover-chosen witness, so it is exposed here to be pinned.
    pub public_inputs: [String; 3],
    pub encoded_proof: String,
    pub raw_proof: String,
    pub plonk_vkey_hash: [u8; 32],
}

/// A zero-knowledge proof generated by the Groth16 protocol with a Base64 encoded gnark Groth16
/// proof.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Groth16Bn254Proof {
    /// `[vkey_hash, committed_values_digest, vk_root]`.
    ///
    /// The third is the recursion verifying-key-allowlist root: inside the
    /// tree it is a prover-chosen witness, so it is exposed here to be pinned.
    pub public_inputs: [String; 3],
    pub encoded_proof: String,
    pub raw_proof: String,
    pub groth16_vkey_hash: [u8; 32],
}

/// An empty proof structure for DV-SNARK
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct DvSnarkBn254Proof {}
