[package]
name = "groth16-verifier-host"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
zkm2-sdk = { workspace = true }

[build-dependencies]
zkm2-build = { workspace = true }

[features]
cuda = ["zkm2-sdk/cuda"]
