/-
  Generated by `cargo run -p zkm-picus -- --chip Program --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic
import ZirenDet.Safe

set_option maxRecDepth 4000000
set_option maxHeartbeats 0
set_option picus.safeHeartbeats 40000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.Program

open ZirenDet

/-! ### Module `Program` -/
namespace Program

/-- Abstract helper: 0 input(s), 0 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end Program

end ZirenDet.Chips.Program
