[package]
name = "bls-decompress-test"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
zkm-zkvm = { path = "../../../../crates/zkvm/entrypoint" }
zkm-lib = { path = "../../../../crates/zkvm/lib" }
