[package]
name = "rsa-host"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
rsa = "0.6"
zkm2-sdk = { workspace = true }

[build-dependencies]
zkm2-build = { workspace = true }
