[package]
name = "zkm2-recursion-core"
description = "zkMIPS"
readme = "../../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
p3-field = { workspace = true }
p3-util = { workspace = true }
p3-baby-bear = { workspace = true }
p3-air = { workspace = true }
p3-matrix = { workspace = true }
p3-maybe-rayon = { workspace = true }
p3-poseidon2 = { workspace = true }
p3-symmetric = { workspace = true }
tracing = { workspace = true }
hashbrown = { workspace = true, features = ["serde"] }
itertools = { workspace = true }
p3-bn254-fr = { workspace = true }
p3-merkle-tree = { workspace = true }
p3-commit = { workspace = true }
p3-dft = { workspace = true }
p3-challenger = { workspace = true }
p3-fri = { workspace = true }
zkhash = "0.2.0"
ff = { version = "0.13", features = ["derive", "derive_bits"] }
serde = { workspace = true, features = ["derive", "rc"] }
backtrace = { version = "0.3.71", features = ["serde"] }
static_assertions = "1.1.0"
thiserror = "1.0.60"
vec_map = "0.8.2"

zkm2-derive = { workspace = true }
zkm2-stark = { workspace = true }

[dev-dependencies]
rand = "0.8.5"
