name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v2
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/zkMIPS/toolchain/refs/heads/main/setup.sh | sh
      - name: Cargo build
        run: source ~/.zkm-toolchain/env && RUSTFLAGS="-C target-cpu=native" cargo build --release
      - name: Cargo test dev groth16
        run: source ~/.zkm-toolchain/env && RUSTFLAGS="-C target-cpu=native" ZKM_DEV=true cargo test -r test_e2e_prove_groth16
      - name: Cargo test dev plonk
        run: source ~/.zkm-toolchain/env && RUSTFLAGS="-C target-cpu=native" ZKM_DEV=true cargo test -r test_e2e_prove_plonk 
      - name: Cargo test prod groth16
        run: source ~/.zkm-toolchain/env && RUSTFLAGS="-C target-cpu=native" cargo test -r test_verify_groth16 --features ark
      - name: Cargo test prod plonk
        run: source ~/.zkm-toolchain/env && RUSTFLAGS="-C target-cpu=native" cargo test -r test_verify_plonk 
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/zkMIPS/toolchain/refs/heads/main/setup.sh | sh
      - run: source ~/.zkm-toolchain/env && cd crates/test-artifacts && cargo build && cd ../..
      - run: rustup component add clippy
      - run: cargo clippy --all-targets -- -D warnings
